---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2
        with:
          path: workflow
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install 'ansible<2.10'
          python3 -m pip install yamllint
          python3 -m pip install ansible-lint
          python3 -m pip install testinfra
          python3 -m pip install molecule[docker] docker
      - name: Test with molecule
        run: |
          ansible --version
          python --version
          molecule --version
          cd workflow
          molecule test
